config/routes.rb
Rails.application.routes.draw do
  root 'home#home'
  resources :uniforms
  resources :forms
  resources :projects
  resources :meetings
  resources :leaders
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/uniforms_controller.rb
class UniformsController < ApplicationController
  before_action :set_uniform, only: [:show, :edit, :update, :destroy]

  # GET /uniforms
  # GET /uniforms.json
  def index
    @uniforms = Uniform.all
  end

  # GET /uniforms/1
  # GET /uniforms/1.json
  def show
  end

  # GET /uniforms/new
  def new
    @uniform = Uniform.new
  end

  # GET /uniforms/1/edit
  def edit
  end

  # POST /uniforms
  # POST /uniforms.json
  def create
    @uniform = Uniform.new(uniform_params)

    respond_to do |format|
      if @uniform.save
        format.html { redirect_to @uniform, notice: 'Uniform was successfully created.' }
        format.json { render :show, status: :created, location: @uniform }
      else
        format.html { render :new }
        format.json { render json: @uniform.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /uniforms/1
  # PATCH/PUT /uniforms/1.json
  def update
    respond_to do |format|
      if @uniform.update(uniform_params)
        format.html { redirect_to @uniform, notice: 'Uniform was successfully updated.' }
        format.json { render :show, status: :ok, location: @uniform }
      else
        format.html { render :edit }
        format.json { render json: @uniform.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uniforms/1
  # DELETE /uniforms/1.json
  def destroy
    @uniform.destroy
    respond_to do |format|
      format.html { redirect_to uniforms_url, notice: 'Uniform was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_uniform
      @uniform = Uniform.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def uniform_params
      params.require(:uniform).permit(:name)
    end
end

app/helpers/uniforms_helper.rb
module UniformsHelper
end

app/views/uniforms/_form.html.erb
<%= form_with(model: uniform, local: true) do |form| %>
  <% if uniform.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(uniform.errors.count, "error") %> prohibited this uniform from being saved:</h2>

      <ul>
      <% uniform.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name, id: :uniform_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/uniforms/edit.html.erb
<h1>Editing Uniform</h1>

<%= render 'form', uniform: @uniform %>

<%= link_to 'Show', @uniform %> |
<%= link_to 'Back', uniforms_path %>

app/views/uniforms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Uniforms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @uniforms.each do |uniform| %>
      <tr>
        <td><%= uniform.name %></td>
        <td><%= link_to 'Show', uniform %></td>
        <td><%= link_to 'Edit', edit_uniform_path(uniform) %></td>
        <td><%= link_to 'Destroy', uniform, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Uniform', new_uniform_path %>

app/views/uniforms/new.html.erb
<h1>New Uniform</h1>

<%= render 'form', uniform: @uniform %>

<%= link_to 'Back', uniforms_path %>

app/views/uniforms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @uniform.name %>
</p>

<%= link_to 'Edit', edit_uniform_path(@uniform) %> |
<%= link_to 'Back', uniforms_path %>